@startuml

title Тёплый дом

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(admin, "Администратор", "Администратор системы")
Person(user, "Пользователь", "Пользователь системы")

System(system, "Система управления отоплением")

Rel(admin, system, "Настраивает устройства, управляет пользователями")
Rel(user, system, "Просматривает температуру, управляет отоплением")

System_Ext(sensors, "Датчики температуры", "IoT устройства")

Rel(system, sensors, "Запрашивает показания")
Rel(system, sensors, "Отправляет команды управления")

@enduml